name: Build N-Body Simulator

on:
  push:
    tags:
      - 'v*'  # Run on tag push of pattern v*, like v1.0.0, v20.15.10
  workflow_dispatch:  # Allow manual trigger of workflow

permissions:
  contents: write  # Add explicit permission to create releases

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MinGW using chocolatey
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install mingw -y

      - name: Add MinGW to PATH
        run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install SDL2
        run: |
          mkdir -p C:/SDL2
          curl -L https://github.com/libsdl-org/SDL/releases/download/release-2.26.5/SDL2-devel-2.26.5-mingw.zip -o SDL2.zip
          7z x SDL2.zip -oC:/
          dir C:/SDL2-2.26.5/x86_64-w64-mingw32
          dir C:/SDL2-2.26.5/x86_64-w64-mingw32/include
          # Create SDL2 structure
          mkdir -p C:/SDL2/include/SDL2
          mkdir -p C:/SDL2/lib
          
          # Copy header files to maintain SDL2/SDL.h structure
          Copy-Item -Path C:/SDL2-2.26.5/x86_64-w64-mingw32/include/*.h -Destination C:/SDL2/include/SDL2/ -Recurse
          Copy-Item -Path C:/SDL2-2.26.5/x86_64-w64-mingw32/lib/* -Destination C:/SDL2/lib/ -Recurse
          
          # Check the final structure
          dir C:/SDL2/include/SDL2

      - name: Build with MinGW
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:/SDL2 ..
          mingw32-make VERBOSE=1

      - name: Create Release Zip
        run: |
          mkdir release
          copy build\ParticlesDemo.exe release\particles-demo.exe
          copy C:\SDL2-2.26.5\x86_64-w64-mingw32\bin\SDL2.dll release\
          xcopy /E /I assets release\assets
          cd release
          7z a ..\n-body-simulator-windows.zip *

      - name: Upload Windows Build
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: n-body-simulator-windows.zip
          token: ${{ github.token }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

      - name: Build with GCC
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Create Release Tar
        run: |
          mkdir -p release
          cp build/ParticlesDemo release/particles-demo
          cp -r assets release/
          cd release
          tar -czvf ../n-body-simulator-linux.tar.gz *

      - name: Upload Linux Build
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: n-body-simulator-linux.tar.gz
          token: ${{ github.token }}